### ISSUE TITLE
Any idea about image caption implementation.

### ISSUE THREAD

**Issue by Ma-Weijian** [lucidrains/transfusion-pytorch#26]
HI there, 

Thanks for the great reproduction!

I just wonder if there is any plan to implement image caption under the framework proposed in tranfusion paper.

Thanks

**Comment by lucidrains** [comment]
@Ma-Weijian the example [here](https://github.com/lucidrains/transfusion-pytorch/blob/main/train_mnist.py#L24) is by default captioning - for text-to-image, just set this to `True`

**Comment by lucidrains** [comment]
@Ma-Weijian had it backwards, my bad!

**Comment by mijanur132** [comment]
This script generates following error when turned "IMAGE_AFTER_TEXT = False" for image captioning , I have tried multiple times and got same result. 

Traceback (most recent call last):
  File "/lustre/orion/stf218/proj-shared/brave/transfusion-pytorch/train_mnist.py", line 130, in <module>
    one_multimodal_sample = ema_model.sample(max_length = 384)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccs/home/palashmr/packages/miniconda/pyt_env/transfusion/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/orion/stf218/proj-shared/brave/transfusion-pytorch/transfusion_pytorch/transfusion.py", line 154, in inner
    out = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/orion/stf218/proj-shared/brave/transfusion-pytorch/transfusion_pytorch/transfusion.py", line 1322, in sample
    *_, last_modality_sample = modality_sample
    ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected at least 1, got 0)

**Comment by lucidrains** [comment]
ah I'll have to get back to you on this next week, it is the weekend here.
