### ISSUE TITLE
Bug: modality_token_transform is empty?

### ISSUE THREAD

**Issue by GindaChen** [lucidrains/transfusion-pytorch#6]
@lucidrains Really nice repo!

I think I found a small bug introduced in [commit 189413](https://github.com/GindaChen/transfusion-pytorch/commit/1894132b93e614690e7ff13690ebc76c5485a62b). Running the [2 examples in usage README file](https://github.com/GindaChen/transfusion-pytorch?tab=readme-ov-file#usage) will give me the following error

```bash
Traceback (most recent call last):
  File "/mount/mnemosyneameyswedan/mnemosyne-profiling/junda/transys/transfusion-pytorch/../spec-transfusion/try_transfusion.py", line 4, in <module>
    model = Transfusion(
  File "/mount/mnemosyneameyswedan/mnemosyne-profiling/junda/transys/transfusion-pytorch/transfusion_pytorch/transfusion.py", line 559, in __init__
    modality_token_transform = [default(transform, identity) for transform in modality_token_transform]
TypeError: 'NoneType' object is not iterable
```

I thought it was just a default value problem, and simply added a line
```python
class Transfusion(Module):
  def __init__(self):
    modality_token_transform = default(modality_token_transform, [])
```
but it doesn't fix the issue:
```bash
Traceback (most recent call last):
  File "/mount/mnemosyneameyswedan/mnemosyne-profiling/junda/transys/transfusion-pytorch/../spec-transfusion/try_transfusion.py", line 31, in <module>
    loss, breakdown = model(
  File "/mount/mnemosyneameyswedan/mnemosyne-profiling/junda/transys/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mount/mnemosyneameyswedan/mnemosyne-profiling/junda/transys/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mount/mnemosyneameyswedan/mnemosyne-profiling/junda/transys/transfusion-pytorch/transfusion_pytorch/transfusion.py", line 629, in forward
    post_encode_transform = self.modality_token_transform[modality_type]
IndexError: list index out of range
```

What is the `modality_token_transform` used for?

**Comment by lucidrains** [comment]
oops! should be fixed 🙏

**Comment by lucidrains** [comment]
@GindaChen i'm working my way out towards accepting the vae encoder and decoder

the transform would take care of `channel height width` format to `(height width) = seq channel`

**Comment by GindaChen** [comment]
Thanks!
